### ISSUE TITLE
Repo down ?

### ISSUE THREAD

**Issue by ydeshayes** [joscha/play-easymail#33]
Hello, 
I can't get your plugin with: 
  "play-easymail (release)" at "http://joscha.github.io/play-easymail/repo/releases/",
  "play-easymail (snapshot)" at "http://joscha.github.io/play-easymail/repo/snapshots/"

Are your repo down ?

**Comment by joscha** [comment]
The latest versions are not published via github any more, but centrally, so you can just load them directly without using any resolver from sonatype: http://search.maven.org/#search%7Cga%7C1%7Cplay-easymail

**Comment by ydeshayes** [comment]
Ok thanks, I will change the sample app build.sbt.
