### ISSUE TITLE
Verify that mail was sent

### ISSUE THREAD

**Issue by CelloPt** [joscha/play-easymail#36]
Hello!

I was testing my application with my google account as smtp server... I noticed that when setting the account password blank, I don't receive any warning or error and, of course, the e-mail is not delivered. This is crucial for me since I'm storing the e-mails on a DB to be sent again if they were not sent (I keep an e-mail history).

Is there any possibility to verify if an e-mail was effectively sent? If there is, how?

Thanks for the help!

**Comment by joscha** [comment]
due to the async nature of the mailer this is not that easy. I guess logging would be a possibility, however having sent an email does not mean the recipient got it anyway.
As to the authentication problem, I am happy to merge a pull request if you open one for that.

**Comment by joscha** [comment]
Timed out. We can re-open this if needed.
