### ISSUE TITLE
0.7.0 already on Maven Sonatype?

### ISSUE THREAD

**Issue by pbelmann** [joscha/play-easymail#44]
You have stated in your commit https://github.com/joscha/play-easymail/commit/2ca7b73095734524a608f931255b159565cdea12 that play-easymail 0.7.0 is available on sonatype.
But I can not find it.
Could you upload it to Sonatype?

**Comment by mkurz** [comment]
Right now there is "just" a snapshot available, not the final version.
Just use `0.7.0-SNAPSHOT` instead.
Make sure you also add
`resolvers += Resolver.sonatypeRepo("snapshots")`
to your `build.sbt`.


Please let us know if you run into any issues, so we can soon release the final version, thanks!

**Comment by pbelmann** [comment]
Thank you,
the resolver was missing.
