### ISSUE TITLE
Attachment Support

### ISSUE THREAD

**Issue by pbelmann** [joscha/play-easymail#45]
play-easymail 0.7.0 attachment support?

**Comment by mkurz** [comment]
Yes it has attachment support. Have a look at the sample:
https://github.com/joscha/play-easymail/blob/01baa98d3e55017db27deb4524cebcd8e723096c/samples/play-easymail-usage/app/controllers/Application.java#L60-L66

**Comment by pbelmann** [comment]
thx again!
