### ISSUE TITLE
0.8.x on maven central

### ISSUE THREAD

**Issue by pbelmann** [joscha/play-easymail#48]
Hi.

could you please make your play-easymail version 0.8.x available on maven central?

**Comment by albuch** [comment]
Hi @joscha,
any chance 0.8.1 is published as a release?

**Comment by joscha** [comment]
Should show up here in a few minutes: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.feth%22%20AND%20a%3A%22play-easymail_2.11%22
