### ISSUE TITLE
does'nt work in play 2.5.9 version 0.8.1

### ISSUE THREAD

**Issue by leccyril** [joscha/play-easymail#50]
Hi, 

i am using play authenticate conf ;

Mailer.getDefaultMailer().sendMail(
    "Your subject",
    "Your text body",
    "recipient@email.com"
);

the class mailer have not method getDefaultMailer, just sendMail() method...

so i use your sample but with debug mode : 

 # TODO: Disable this in production
    mock=false
    # SMTP server
    # (mandatory)
    # defaults to gmail
    host=smtp.gmail.com

    # SMTP port
    # defaults to 25
    port=587
    #port=465

    # Use TLS
    # for GMail, this should be set to true
    tls=true
	#ssl=no
	# isSSL=true
.....

i have this error : 

Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 587; timeout 60000

with in debug : 

DEBUG SMTP: trying to connect to host "smtp.gmail.com", port 587, isSSL false

i tried tls=no, ssl=true port 465 but same problem

thanks in advance for help

**Comment by joscha** [comment]
According to https://support.google.com/a/answer/176600?hl=en 587 is for TLS, whereas 465 needs SSL. I suspect some other problem, maybe on the network level?

**Comment by leccyril** [comment]
hi, 

thank you for your reactivity, 

i will try it tonight in other network, for information is there any specific configuration to add when we have a proxy ? 

thank you

**Comment by joscha** [comment]
You can have a look here for the settings: https://github.com/playframework/play-mailer

**Comment by leccyril** [comment]
really sorry but i browse all files and no mention to proxy configuration anywhere

**Comment by joscha** [comment]
I do believe it just uses what the Java process is using. Not super sure about that one. play-easymail just uses the play-mailer underneath, so you might have more luck using their forum.

**Comment by leccyril** [comment]
ok not mandatory because i want it works without proxy (just for test in company)... i will test tonight...

is the lib efficient  for huge amount of email to send ? 

compatible freemarker ? 

thank you very much!

**Comment by leccyril** [comment]
It works out of network with proxy.

will test performance later thank you !
