### ISSUE TITLE
Bump play-mailer version to 5.0

### ISSUE THREAD

**Issue by eximius313** [joscha/play-easymail#51]
Can you please bump the version of ```play-mailer``` to 5.0 (it's not M1 anymore) https://github.com/playframework/play-mailer#current-versions

And also why ```play-easymail``` is still a ```SNAPSHOT```?

**Comment by joscha** [comment]
Sure, open a PR, I will merge it.

**Comment by eximius313** [comment]
here you go: https://github.com/joscha/play-easymail/pull/52
